(cl:in-package ros_mavlink_proxy-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME_USEC-VAL
          TIME_USEC
          XACC-VAL
          XACC
          YACC-VAL
          YACC
          ZACC-VAL
          ZACC
          XGYRO-VAL
          XGYRO
          YGYRO-VAL
          YGYRO
          ZGYRO-VAL
          ZGYRO
          XMAG-VAL
          XMAG
          YMAG-VAL
          YMAG
          ZMAG-VAL
          ZMAG
          ABS_PRESSURE-VAL
          ABS_PRESSURE
          DIFF_PRESSURE-VAL
          DIFF_PRESSURE
          PRESSURE_ALT-VAL
          PRESSURE_ALT
          TEMPERATURE-VAL
          TEMPERATURE
          FIELDS_UPDATED-VAL
          FIELDS_UPDATED
          ID-VAL
          ID
          ORIGIN_SYSTEM_ID-VAL
          ORIGIN_SYSTEM_ID
))