(cl:defpackage ros_mavlink_proxy-msg
  (:use )
  (:export
   "<ALTITUDE>"
   "ALTITUDE"
   "<ATTITUDE>"
   "ATTITUDE"
   "<COMMANDLONG>"
   "COMMANDLONG"
   "<GLOBALPOSITIONINT>"
   "GLOBALPOSITIONINT"
   "<HEARTBEAT>"
   "HEARTBEAT"
   "<HIGHRESIMU>"
   "HIGHRESIMU"
   "<LOCALPOSITIONNED>"
   "LOCALPOSITIONNED"
   "<SETPOSITIONTARGETGLOBALINT>"
   "SETPOSITIONTARGETGLOBALINT"
   "<SETPOSITIONTARGETLOCALNED>"
   "SETPOSITIONTARGETLOCALNED"
   "<POLLING_OR_SENDSTREAM>"
   "POLLING_OR_SENDSTREAM"
  ))

