(cl:in-package ros_mavlink_proxy-msg)
(cl:export '(HEADER-VAL
          HEADER
          TARGET_SYSTEM-VAL
          TARGET_SYSTEM
          TARGET_COMPONENT-VAL
          TARGET_COMPONENT
          COMMAND-VAL
          COMMAND
          CONFIRMATION-VAL
          CONFIRMATION
          PARAM1-VAL
          PARAM1
          PARAM2-VAL
          PARAM2
          PARAM3-VAL
          PARAM3
          PARAM4-VAL
          PARAM4
          PARAM5-VAL
          PARAM5
          PARAM6-VAL
          PARAM6
          PARAM7-VAL
          PARAM7
          ORIGIN_SYSTEM_ID-VAL
          ORIGIN_SYSTEM_ID
          TARGET_SYSTEM_ID-VAL
          TARGET_SYSTEM_ID
))